#!/usr/bin/env python3
"""Generate Software/Libs/Header/uoom_qr.h -- the download link as a QR code.

The port's first screen, before there is a WAD to draw DOOM's own font from,
has to tell someone holding a watch where to get a 4 MB file. A URL they would
have to retype from a 1.4-inch round screen is not that; a QR code is.

Encoded at build time rather than on the watch, because the URL is fixed and a
Reed-Solomon encoder is a lot of flash to carry for one static image. The
result is 33x33 modules packed one bit each -- 137 bytes.

Sizing is set by the panel, not by taste. The active area is a circle of radius
120, so the largest square that fits is r*sqrt(2) = 169 px. A version 4 symbol
is 33 modules, plus the 4-module quiet zone the spec requires on each side, is
41 -- and 169/41 = 4 pixels per module, 164 px overall. That is 24 mm on this
panel and a module of 0.59 mm, which any phone reads from about 10 cm.

Error correction M rather than L: at this length the short URL needs version 4
either way, so the sturdier level is free.

    tools/make_qr.py                 regenerate with the default URL
    tools/make_qr.py --url ... --preview qr.png
"""
import argparse
import sys
from pathlib import Path

# The blob page, not the /raw/ link: scanning a QR should land you on a page
# with a download button, not start four megabytes over whatever connection
# the phone happens to be on. Costs nothing -- both spellings need a
# version 4 symbol, so the code is the same size either way.
DEFAULT_URL = "https://github.com/szymonkonopek/uoom/blob/main/wad/DOOM1.WAD"
ERROR_LEVEL = "M"

# Must match UOOM_PANEL_RADIUS in uoom_config.h.
PANEL_RADIUS = 120
QUIET = 4


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=DEFAULT_URL)
    ap.add_argument("--out", type=Path,
                    default=Path("Software/Libs/Header/uoom_qr.h"))
    ap.add_argument("--preview", type=Path,
                    help="also write a PNG, to check it scans before flashing")
    args = ap.parse_args()

    try:
        import segno
    except ImportError:
        print("needs segno:  .venv/bin/pip install segno", file=sys.stderr)
        return 1

    qr = segno.make(args.url, error=ERROR_LEVEL, micro=False)
    size = qr.symbol_size(scale=1, border=0)[0]

    safe = int(PANEL_RADIUS * 46341 / 32768)        # r * sqrt(2)
    scale = safe // (size + 2 * QUIET)
    if scale < 3:
        print(f"{size}x{size} at {scale}px/module is too small to scan; "
              f"shorten the URL", file=sys.stderr)
        return 1

    rows = [
        [bool(m) for m in row]
        for row in qr.matrix_iter(scale=1, border=0)
    ]

    bits = bytearray((size * size + 7) // 8)
    for y, row in enumerate(rows):
        for x, dark in enumerate(row):
            if dark:
                i = y * size + x
                bits[i >> 3] |= 1 << (i & 7)

    body = []
    for i in range(0, len(bits), 12):
        body.append("    " + " ".join(f"0x{b:02x}," for b in bits[i:i + 12]))

    args.out.write_text(f'''/* uoom_qr.h -- generated by tools/make_qr.py, do not edit
 *
 * {args.url}
 *
 * Version {qr.version} symbol, error correction {ERROR_LEVEL}, {size}x{size}
 * modules, one bit each, row-major, bit 0 of byte 0 being the top-left. The
 * {QUIET}-module quiet zone is not stored -- it is drawn as background, which
 * costs nothing and keeps this array to {len(bits)} bytes.
 *
 * At {scale} px per module the symbol and its quiet zone come to
 * {(size + 2 * QUIET) * scale} px, inside the {safe} px square that fits the
 * round panel.
 */

#ifndef UOOM_QR_H_INCLUDED
#define UOOM_QR_H_INCLUDED

#include <stdint.h>

#define UOOM_QR_URL     "{args.url}"
#define UOOM_QR_SIZE    {size}
#define UOOM_QR_QUIET   {QUIET}
#define UOOM_QR_SCALE   {scale}

static const uint8_t uoom_qr_bits[{len(bits)}] = {{
{chr(10).join(body)}
}};

#endif /* UOOM_QR_H_INCLUDED */
''')
    print(f"{args.out}: version {qr.version}-{ERROR_LEVEL}, {size}x{size}, "
          f"{scale}px/module -> {(size + 2 * QUIET) * scale}px of {safe}")

    if args.preview:
        qr.save(str(args.preview), scale=scale, border=QUIET,
                dark="black", light="white")
        print(f"{args.preview}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
