#!/usr/bin/env python3
"""Generate Software/Libs/Header/uoom_font.h from the readable art below.

Why a font at all: the port needs to say "no WAD found" before a WAD exists to
draw DOOM's own font from, and it needs an on-screen frame-time readout,
because a watch has no debugger attached and no console you can watch.

3x5 glyphs, one byte per column, bit 0 = top row. 3 bytes per glyph. Drawn at
2x or 3x on a 240px panel, this is comfortably readable.
"""
from pathlib import Path

GLYPHS = {
    ' ': ("...", "...", "...", "...", "..."),
    'A': (".#.", "#.#", "###", "#.#", "#.#"),
    'B': ("##.", "#.#", "##.", "#.#", "##."),
    'C': (".##", "#..", "#..", "#..", ".##"),
    'D': ("##.", "#.#", "#.#", "#.#", "##."),
    'E': ("###", "#..", "##.", "#..", "###"),
    'F': ("###", "#..", "##.", "#..", "#.."),
    'G': (".##", "#..", "#.#", "#.#", ".##"),
    'H': ("#.#", "#.#", "###", "#.#", "#.#"),
    'I': ("###", ".#.", ".#.", ".#.", "###"),
    'J': ("..#", "..#", "..#", "#.#", ".#."),
    'K': ("#.#", "#.#", "##.", "#.#", "#.#"),
    'L': ("#..", "#..", "#..", "#..", "###"),
    'M': ("#.#", "###", "###", "#.#", "#.#"),
    'N': ("#.#", "###", "###", "#.#", "#.#"),
    'O': (".#.", "#.#", "#.#", "#.#", ".#."),
    'P': ("##.", "#.#", "##.", "#..", "#.."),
    'Q': (".#.", "#.#", "#.#", "###", "..#"),
    'R': ("##.", "#.#", "##.", "#.#", "#.#"),
    'S': (".##", "#..", ".#.", "..#", "##."),
    'T': ("###", ".#.", ".#.", ".#.", ".#."),
    'U': ("#.#", "#.#", "#.#", "#.#", "###"),
    'V': ("#.#", "#.#", "#.#", "#.#", ".#."),
    'W': ("#.#", "#.#", "###", "###", "#.#"),
    'X': ("#.#", "#.#", ".#.", "#.#", "#.#"),
    'Y': ("#.#", "#.#", ".#.", ".#.", ".#."),
    'Z': ("###", "..#", ".#.", "#..", "###"),
    '0': ("###", "#.#", "#.#", "#.#", "###"),
    '1': (".#.", "##.", ".#.", ".#.", "###"),
    '2': ("##.", "..#", ".#.", "#..", "###"),
    '3': ("##.", "..#", ".#.", "..#", "##."),
    '4': ("#.#", "#.#", "###", "..#", "..#"),
    '5': ("###", "#..", "##.", "..#", "##."),
    '6': (".##", "#..", "###", "#.#", "###"),
    '7': ("###", "..#", ".#.", ".#.", ".#."),
    '8': ("###", "#.#", "###", "#.#", "###"),
    '9': ("###", "#.#", "###", "..#", "##."),
    '.': ("...", "...", "...", "...", ".#."),
    ',': ("...", "...", "...", ".#.", "#.."),
    ':': ("...", ".#.", "...", ".#.", "..."),
    '-': ("...", "...", "###", "...", "..."),
    '+': ("...", ".#.", "###", ".#.", "..."),
    '=': ("...", "###", "...", "###", "..."),
    '/': ("..#", "..#", ".#.", "#..", "#.."),
    '!': (".#.", ".#.", ".#.", "...", ".#."),
    '?': ("##.", "..#", ".#.", "...", ".#."),
    '%': ("#.#", "..#", ".#.", "#..", "#.#"),
    '(': (".#.", "#..", "#..", "#..", ".#."),
    ')': (".#.", "..#", "..#", "..#", ".#."),
    '*': ("#.#", ".#.", "###", ".#.", "#.#"),
    '#': ("#.#", "###", "#.#", "###", "#.#"),
    '<': ("..#", ".#.", "#..", ".#.", "..#"),
    '>': ("#..", ".#.", "..#", ".#.", "#.."),
}

W, H = 3, 5


def columns(rows):
    out = []
    for x in range(W):
        bits = 0
        for y in range(H):
            if rows[y][x] == '#':
                bits |= 1 << y
        out.append(bits)
    return out


def main():
    order = sorted(GLYPHS)
    lines = [
        "/* uoom_font.h -- GENERATED by tools/make_font.py, do not edit.",
        " *",
        " * 3x5 glyphs. uoom_font_cols[] holds three column bytes per glyph;",
        " * bit 0 is the top row. Look a character up in uoom_font_chars[].",
        " */",
        "#ifndef UOOM_FONT_H_INCLUDED",
        "#define UOOM_FONT_H_INCLUDED",
        "",
        "#include <stdint.h>",
        "",
        f"#define UOOM_FONT_COLS {W}",
        f"#define UOOM_FONT_ROWS {H}",
        f"#define UOOM_FONT_COUNT {len(order)}",
        "",
        "static const char uoom_font_chars[] =",
    ]
    # emit the charset as a C string, escaping what needs it
    esc = "".join(
        "\\\\" if c == "\\" else '\\"' if c == '"' else c for c in order
    )
    lines.append(f'    "{esc}";')
    lines.append("")
    lines.append("static const uint8_t uoom_font_cols[UOOM_FONT_COUNT][UOOM_FONT_COLS] = {")
    for c in order:
        cols = columns(GLYPHS[c])
        shown = c if c not in ('\\', '"') else '\\' + c
        lines.append("    { 0x%02X, 0x%02X, 0x%02X },   /* '%s' */" % (*cols, shown))
    lines.append("};")
    lines.append("")
    lines.append("#endif /* UOOM_FONT_H_INCLUDED */")

    out = Path(__file__).resolve().parent.parent / "Software/Libs/Header/uoom_font.h"
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}  {len(order)} glyphs, {len(order) * W} bytes of table")


if __name__ == "__main__":
    main()
